# Generated by Django 3.1.4 on 2023-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='porfolio101'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='porfolio101'),
        ),
        migrations.AddField(
            model_name='workhistorymodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='porfolio101'),
        ),
    ]
